# InvestESG
domain: InvestESG
num_investors: 3
initial_climate_event_probability: 0.5
market_performance_baseline: 1.1
market_performance_variance: 0
allow_resilience_investment: True
allow_greenwash_investment: False
company_esg_score_observable: True
action_capping: 0.05
max_steps: 100
company_attributes:
 - capital: 10
   climate_risk_exposure: 0.07
   beta: 0
 - capital: 10
   climate_risk_exposure: 0.07
   beta: 0
 - capital: 10
   climate_risk_exposure: 0.07
   beta: 0
 - capital: 10
   climate_risk_exposure: 0.07
   beta: 0
 - capital: 10
   climate_risk_exposure: 0.07
   beta: 0

investor_attributes:
 - capital: 16.7
   esg_preference: 1
 - capital: 16.7
   esg_preference: 1
 - capital: 16.7
   esg_preference: 1

agent_policies:
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5
 - mode: "PPO"
   clip_eps: 0.2
   entropy_coef: 0.01
   value_loss_coef: 0.5